#!/bin/bash -l
#$ -P lejlab2
#$ -pe omp 4
#$ -l mem_per_core=4G
#$ -cwd
module load freesurfer/7.4.1
source $FREESURFER_HOME/SetUpFreeSurfer.sh

# Arguments
input_label=$1          # the segmentation file (.mgz or .nii.gz)
like_img=$2             # the target/original MRI file (.nii.gz)
out_label=$3            # output filename

echo "Resampling $input_label to match $like_img"
mri_convert --resample_type nearest "$input_label" --like "$like_img" "$out_label"